version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    ports:
      - 8080:80
    env_file:
      - ./src/shared/.env
    volumes:
      - ./src/shared:/shared
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vlan
  client:
    container_name: client
    build:
      context: ./src
      dockerfile: ./client/Dockerfile
    ports:
      - 8081:8080
    env_file:
      - ./src/shared/.env
    volumes:
      - ./src/client:/app/vue
      - /app/vue/node_modules
    depends_on:
      - server
    networks:
      - vlan
  game:
    container_name: game
    build:
      context: ./src
      dockerfile: ./game/Dockerfile
    ports:
      - 8082:8080
    env_file:
      - ./src/shared/.env
    volumes:
      - ./src/game:/app/vue
      - /app/vue/node_modules
    depends_on:
      - server
    networks:
      - vlan
  server:
    container_name: server
    build:
      context: ./src
      dockerfile: ./server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/server:/app/api
      - /app/node_modules
    networks:
      - vlan
    env_file:
      - ./src/shared/.env
    depends_on:
      - mongoDB
  mongoDB:
    container_name: mongoDB
    image: mongo:4.4.18
    ports:
      - 27017:27017
    env_file:
      - ./src/shared/.env
    environment:
      MONGO_INITDB_DATABASE: SawThat
      MONGO_INITDB_ROOT_USERNAME: sawthat
      MONGO_INITDB_ROOT_PASSWORD: sawthatsecretpass
    volumes:
      - ./src/shared:/shared
      - ./database:/data/db
    networks:
      - vlan
networks:
  vlan: