version: '3.7'
services:
  caddy:
    container_name: caddy
    image: caddy:2.0.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - vlan
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./client:/app/vue
      - /app/vue/node_modules
    depends_on:
      - backend
    networks:
      - vlan
  game:
    container_name: game
    build:
      context: ./game
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    volumes:
      - ./game:/app/vue
      - /app/vue/node_modules
    depends_on:
      - backend
    networks:
      - vlan
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/api
      - /app/api/node_modules
    networks:
      - vlan
    env_file:
      - ./server/.env
  mongoDB:
    container_name: mongoDB
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ./server/.env
    environment:
      MONGO_INITDB_DATABASE: SawThat
      MONGO_INITDB_ROOT_USERNAME: sawthat
      MONGO_INITDB_ROOT_PASSWORD: sawthatsecretpass
    volumes:
      - ./mongoDB:/data/db
    networks:
      - vlan
networks:
  vlan:
volumes: