version: '3.7'
services:
  caddy:
    container_name: caddy
    image: caddy:2.0.0-alpine
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./src/shared/.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - vlan
  client:
    container_name: client
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - ./src/shared/.env
    volumes:
      - ./src/client:/app/vue
      - /app/vue/node_modules
    depends_on:
      - server
    networks:
      - vlan
  game:
    container_name: game
    build:
      context: ./src/game
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    env_file:
      - ./src/shared/.env
    volumes:
      - ./src/game:/app/vue
      - /app/vue/node_modules
    depends_on:
      - server
    networks:
      - vlan
  server:
    container_name: server
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/server:/app/api
      - /app/node_modules
    networks:
      - vlan
    env_file:
      - ./src/shared/.env
  mongoDB:
    container_name: mongoDB
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ./src/shared/.env
    environment:
      MONGO_INITDB_DATABASE: SawThat
      MONGO_INITDB_ROOT_USERNAME: sawthat
      MONGO_INITDB_ROOT_PASSWORD: sawthatsecretpass
    volumes:
      - ./database:/data/db
    networks:
      - vlan
networks:
  vlan: