version: '3.7'
services:
  api-docs:
    container_name: api-docs
    image: redocly/redoc
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - vlan
    security_opt:
      - apparmor:unconfined
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    expose:
      - 80 # internal HTTP port
    volumes:
      - ./backend/swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
     - SPEC_URL=/swagger.yaml
networks:
  vlan:
volumes: